# Generated by Django 3.1.6 on 2021-02-05 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgamers',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelupapi.event'),
        ),
    ]
