# Generated by Django 3.1.6 on 2021-02-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_auto_20210205_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='schduler',
            new_name='scheduler',
        ),
    ]
