# Generated by Django 3.1.6 on 2021-02-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20210205_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventGamers',
            new_name='EventGamer',
        ),
        migrations.RenameModel(
            old_name='Games',
            new_name='Game',
        ),
    ]
